-- upgrade --
CREATE TABLE IF NOT EXISTS "guild" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);
CREATE TABLE IF NOT EXISTS "members" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);
CREATE TABLE IF NOT EXISTS "warn" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "reason" VARCHAR(1024) NOT NULL,
    "guild_id" BIGINT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE,
    "issuer_id" BIGINT NOT NULL REFERENCES "members" ("id") ON DELETE CASCADE,
    "user_id" BIGINT NOT NULL REFERENCES "members" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
