-- upgrade --
CREATE TABLE IF NOT EXISTS "autorole" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "guild_id" BIGINT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE
);;
ALTER TABLE "guild" ADD "autorole" INT NOT NULL  DEFAULT 0;
CREATE TABLE IF NOT EXISTS "modrole" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "guild_id" BIGINT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "muterole" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "guild_id" BIGINT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "probationrole" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "guild_id" BIGINT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE
);-- downgrade --
ALTER TABLE "guild" DROP COLUMN "autorole";
DROP TABLE IF EXISTS "autorole";
DROP TABLE IF EXISTS "modrole";
DROP TABLE IF EXISTS "muterole";
DROP TABLE IF EXISTS "probationrole";
